import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Row,
  Column,
  Text,
} from "@react-email/components";

interface AdminNotificationProps {
  name: string;
  email: string;
  phone: string;
  course: string;
  workshopDate: string;
  message?: string;
}

export default function AdminNotification({
  name,
  email,
  phone,
  course,
  workshopDate,
  message,
}: AdminNotificationProps) {
  return (
    <Html>
      <Head />
      <Preview>New Workshop Registration Received</Preview>

      <Body
        style={{
          backgroundColor: "#f5f7fa",
          fontFamily: "Arial, sans-serif",
          padding: "30px 0",
        }}
      >
        <Container
          style={{
            maxWidth: "650px",
            margin: "0 auto",
            backgroundColor: "#ffffff",
            borderRadius: "8px",
            border: "1px solid #e5e7eb",
            padding: "30px",
          }}
        >
          <Heading
            style={{
              color: "#0f172a",
              fontSize: "24px",
              marginBottom: "20px",
            }}
          >
            📩 New Workshop Registration
          </Heading>

          <Text style={{ color: "#475569", marginBottom: "20px" }}>
            A new student has registered through the Saturday Workshops
            website.
          </Text>

          <Section>
            <Row>
              <Column>
                <Text>
                  <strong>Name:</strong> {name}
                </Text>

                <Text>
                  <strong>Email:</strong> {email}
                </Text>

                <Text>
                  <strong>Phone:</strong> {phone}
                </Text>

                <Text>
                  <strong>Course:</strong> {course}
                </Text>

                <Text>
                  <strong>Workshop Date:</strong> {workshopDate}
                </Text>

                <Text>
                  <strong>Message:</strong>{" "}
                  {message?.trim() || "No message provided"}
                </Text>
              </Column>
            </Row>
          </Section>

          <Section
            style={{
              marginTop: "30px",
              borderTop: "1px solid #e5e7eb",
              paddingTop: "20px",
            }}
          >
            <Text
              style={{
                fontSize: "13px",
                color: "#64748b",
              }}
            >
              This email was automatically generated by the Saturday Workshops
              website.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}